documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - dev_tutorials/*

"ci":
  - changed-files:
      - any-glob-to-any-file:
          - .azure/*
          - .github/*
          - .github/workflows/*
          - dockers/**/*

"docker":
  - changed-files:
      - any-glob-to-any-file:
          - dockers/**/*
          - .azure/docker-build.yml

"install":
  - changed-files:
      - any-glob-to-any-file:
          - setup.py
          - pyproject.toml
          - MANIFEST.in

"dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - requirements/*
          - requirements.txt
