name: Code updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # on Sundays

jobs:

  precommit-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_GHOST }}

    - name: Set up Python ğŸ
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run pre-commit ğŸ¤–
      continue-on-error: true
      run: |
        pip install -q pre-commit
        pre-commit run --all-files

    - name: Commit changes â†©ï¸
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "pre-commit: apply formatting"