name: Code linting

on: [push]

jobs:

  precommit-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ›ï¸
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_GHOST }}

    - name: Set up Python ğŸ
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run pre-commit ğŸ¤–
      id: precommit
      run: |
        pip install -q pre-commit
        pre-commit run --all-files

    - name: Fixing Pull Request â†©ï¸
      if: always() && github.ref != 'refs/heads/main' && steps.precommit.outcome == 'failure'
      uses: actions-js/push@v1.4
      with:
        github_token: ${{ secrets.PAT_GHOST }}
        message: "pre-commit: running and fixing..."
        branch: ${{ github.ref_name }}
